### ISSUE TITLE
Visual Studio Code not closing upon closing the bunch

### ISSUE THREAD

**Issue by cattapan** [ttscoff/bunch#61] opened 2021-05-14 17:20 UTC
I've created for test purposes only a bunch with only one line:
`Visual Studio Code`

It opens Visual Studio successfully but, upon closing the bunch, VS Code does not get closed. I'm running the beta version Version 1.4.0 (93) and these are the logs:

2021-05-14 18:15:05: ⚪[vs] Open >>>>>>>>>>>>>>>>>>>>>
2021-05-14 18:15:05: ⚪[vs] Launching app (Visual Studio Code)
2021-05-14 18:15:17: ⚪[vs] Closing <<<<<<<<<<<<<<<<<<
2021-05-14 18:15:17: 🟡[vs] Unrecognized item or app not running (Visual Studio Code)

**Comment by ttscoff** [comment] 2021-05-17 18:58
I've noticed VS Code does some weird things when opening projects directly, launching additional instances of itself in the process. I'll have to look into any issues with the way the running app identifies itself.

**Comment by ttscoff** [comment] 2021-05-20 18:05
So this is a bit frustrating. Visual Studio Code launches with that name, but once it's running, it identifies as just "Code". The easy, existing solution is to add a second line with just `Code`. Assuming you don't actually have any apps named "Code", it would then ignore it when opening, but properly quit VS Code when closing (also throwing the "Unrecognized item" error for the original "Visual Studio Code" line, but that's just a warning and is ignored.

Bigger picture, I would need to add specific handling for VS Code to compensate for this. I imagine it affects some other Electron apps as well, but haven't tested with any others. I know apps like Slack behave pretty well in this regard, so maybe it is just VS Code?

**Comment by ttscoff** [comment] 2021-05-20 18:17
I went ahead and added a very specific conversion for VS code that converts the string to "Code" when trying to quit the app. Hopefully there won't be too many other apps that require this kind of special treatment.

Next update will behave as expected for VS, though.

**Closed by ttscoff** 2021-05-20 18:17 UTC

**Comment by subfighter3** [comment] 2023-06-19 14:45
Apparently the issue is still here :(

**Comment by ttscoff** [comment] 2023-06-19 16:36
> Apparently, the issue is still here :(
> 
> I tried adding a single "Visual Studio Code" line and a second "Code" line.
> 
> in both cases, I got the following console log, while VS Code remains open:
> 
> `2023-06-19 17:06:42: 🔴App not running (Code)`

I assume it _was_ working (no other reports since 2021) and then VS Code fixed their runtime app name and broke my fix in the process. Will have to look back into it.

**Comment by subfighter3** [comment] 2023-06-19 16:49
Yep, I think so! If no other app required this kind of specific fix sounds like a piece of good news :)

Thanks a lot for digging into it!
