### ISSUE TITLE
Bunch variable not initialized in Automator workflows

### ISSUE THREAD

**Issue by seishonagon** [ttscoff/bunch#63] opened 2021-05-16 16:19 UTC
I've copied your "Coding" bunch for my own purposes.
I - mostly - got it to work except for the Timing workflow.
It fails by saying "Please ensure that a variable named "Bunch" is defined in the Workflow."
The variable is defined (i downloaded the automator workflow from your article.) I've even deleted and redefined the Bunch variable, but no joy ...
Not sure how I can help debug.

**Comment by ttscoff** [comment] 2021-05-17 19:03
The error is a guess at what went wrong, it might not be accurate. Does the workflow run fine if you execute it directly?

**Comment by ttscoff** [comment] 2021-05-20 17:34
Doing a quick test I can get an error code 2 by triggering an AppleScript error in the Bunch. In the case of the Timing Workflow, it will throw an error if the Project specified doesn't already exist in Timing. So be sure to pass a valid Timing project. (Or, if you're not actually using Timing, that Workflow will fail every time :)).

If you open the Bunch Log (Help->Open Log) you should be able to see the actual error you're getting.

It might be safer to not assume that the error is caused by a missing Bunch variable in the workflow, and instead just point the user to the log, which would offer a more descriptive error message.

**Comment by ttscoff** [comment] 2021-06-19 18:25
Any update on this? Closing for now, but feel free to reopen if you have new information to add.

**Closed by ttscoff** 2021-06-19 18:25 UTC
